name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - develop

jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - name: Running Checkout
        uses: actions/checkout@v3

      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - run: go test
      - run: go run math.go

      - name: Set up sonarqube
        uses: sonarsource/sonarqube-scan-action@master
        with:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Running quality gate
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        with:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: matheussalencar/go-ci:latest